[package]
name = "ua4f"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
env_logger = "0.11.5"
log = "0.4.22"
socks5-server = "0.10.1"
tokio = { version = "1.40.0", features = ["full"] }
