name: 打包并上传IPK文件

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build ${{ matrix.arch }}-${{ matrix.sdk }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_cortex-a53
        sdk:
          - openwrt-22.03
          - SNAPSHOT

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 安装 Rust 工具链
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          target: aarch64-unknown-linux-musl

      - name: 安装依赖项
        run: |
          sudo apt-get update
          sudo apt-get install -y wget xz-utils rsync build-essential musl-tools gcc-aarch64-linux-gnu          

      - name: 安装 musl 目标
        run: rustup target add aarch64-unknown-linux-musl

      - name: 配置链接器
        run: |
          export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=aarch64-linux-gnu-gcc
          export CC=aarch64-linux-gnu-gcc          

      - name: Rust构建
        run: |
          export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=aarch64-linux-gnu-gcc
          export CC=aarch64-linux-gnu-gcc
          cargo clean
          cargo build --release --target aarch64-unknown-linux-musl

      - name: Building packages
        uses: sbwml/openwrt-gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.sdk }}

      - name: 上传IPK文件
        uses: actions/upload-artifact@v3
        with:
          name: ua4f-ipk
          path: build/ua4f_*.ipk
          retention-days: 1
