name: 构建

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装 Rust 工具链
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          target: aarch64-unknown-linux-musl

      - name: 安装依赖项
        run: |
          sudo apt-get update
          sudo apt-get install -y wget xz-utils rsync build-essential musl-tools gcc-aarch64-linux-gnu   

      - name: 安装 musl 目标
        run: rustup target add aarch64-unknown-linux-musl

      - name: 配置链接器
        run: |
          export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=aarch64-linux-gnu-gcc
          export CC=aarch64-linux-gnu-gcc

      - name: 构建
        run: |
          export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=aarch64-linux-gnu-gcc
          export CC=aarch64-linux-gnu-gcc
          cargo clean
          cargo build --release --target aarch64-unknown-linux-musl

      - name: 上传构建
        run: |
          for i in {1..3}; do
            if actions/upload-artifact@v3 --name ua4f --path target/aarch64-unknown-linux-musl/release/ua4f; then
              break
            else
              echo "Upload failed, retrying... ($i)"
              sleep 5
            fi
          done
