name: 构建 IPK 包

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: 构建 IPK 包 - ${{ matrix.arch.simple_name }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch:
          - { simple_name: x86_64, sdk_url: "https://downloads.openwrt.org/releases/23.05.0/targets/x86/64/openwrt-sdk-23.05.0-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz", target: x86_64-unknown-linux-musl, sdk_arch: "x86_64" }
          - { simple_name: aarch64, sdk_url: "https://downloads.openwrt.org/releases/23.05.0/targets/rockchip/armv8/openwrt-sdk-23.05.0-rockchip-armv8_gcc-12.3.0_musl.Linux-x86_64.tar.xz", target: aarch64-unknown-linux-musl, sdk_arch: "aarch64" }
          - { simple_name: armv7, sdk_url: "https://downloads.openwrt.org/releases/23.05.0/targets/mediatek/mt7629/openwrt-sdk-23.05.0-mediatek-mt7629_gcc-12.3.0_musl_eabi.Linux-x86_64.tar.xz", target: armv7-unknown-linux-musleabihf, sdk_arch: "arm_cortex-a7_neon-vfpv4" }

    steps:
      - name: 检出源代码
        uses: actions/checkout@v4

      - name: 从 Cargo.toml 中提取版本号
        id: extract_version
        run: |
          version=$(grep '^version' Cargo.toml | awk -F\" '{print $2}')
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: 安装 Rust 工具链
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          target: ${{ matrix.arch.target }}

      - name: 为 ARM 架构安装依赖
        if: matrix.arch.simple_name != 'x86_64'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu

      - name: 下载并准备 OpenWrt SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y wget xz-utils rsync
          wget ${{ matrix.arch.sdk_url }}
          tar -xf $(basename ${{ matrix.arch.sdk_url }})

          # 确定解压的 SDK 目录
          SDK_DIR=$(find . -maxdepth 1 -type d -name "openwrt-sdk-*")
          if [ -z "$SDK_DIR" ]; then
            echo "错误: 未找到解压后的 SDK 目录！" && exit 1
          fi
          mv "$SDK_DIR" openwrt-sdk
          echo "SDK 已成功解压到 openwrt-sdk。"

      - name: 将本地包复制到 SDK 中
        run: |
          mkdir -p openwrt-sdk/package/ua4f
          cp -r ./openwrt/* openwrt-sdk/package/ua4f
          echo "本地包 'openwrt' 已成功复制到 SDK 的 'ua4f' 包目录中。"

      - name: 配置 SDK 编译 Rust
        run: |
          cd openwrt-sdk
          echo "CONFIG_PACKAGE_ua4f=y" >> .config
          make defconfig
          make package/ua4f/compile V=s -j$(nproc)

      - name: 检查并拷贝 IPK 包
        run: |
          cd openwrt-sdk
          mkdir -p ../output/${{ matrix.arch.simple_name }}
          cp bin/packages/${{ matrix.arch.sdk_arch }}/*/*.ipk ../output/${{ matrix.arch.simple_name }}/ua4f_${{ steps.extract_version.outputs.version }}_${{ matrix.arch.simple_name }}.ipk

      - name: 上传 IPK 包构件
        uses: actions/upload-artifact@v3
        with:
          name: UA4F-${{ matrix.arch.simple_name }}
          path: output/${{ matrix.arch.simple_name }}/ua4f_${{ steps.extract_version.outputs.version }}_${{ matrix.arch.simple_name }}.ipk
          retention-days: 1
          compression-level: 9
